name:                Fractals
version:             0.1.0.0
github:              "kockahonza/Fractals"
license:             BSD3
author:              "Jan Kocka"
maintainer:          "kockahonza@gmail.com"
copyright:           "GPL3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kockahonza/Fractals#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- JuicyPixels
- gloss
- gloss-juicy

library:
  source-dirs: src

executables:
  Fractals-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O1
    - -rtsopts
    # - threaded
    dependencies:
    - Fractals

tests:
  Fractals-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Fractals
